"""initial schema — users, oauth_tokens, email/sender/conversation tables

Revision ID: 0001
Revises:
Create Date: 2026-05-20

Replaces the legacy backend/migrations.py startup ALTER-TABLE script. This is
the alembic baseline — all subsequent schema changes go through autogenerated
revisions. Enables the pgvector extension for future embedding columns
(Step 8 RAG knowledge base).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector — harmless if missing (SQLite tests); only Postgres supports CREATE EXTENSION.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.UniqueConstraint("provider", "user_id", name="uq_oauth_provider_user"),
    )
    op.create_index("ix_oauth_tokens_provider", "oauth_tokens", ["provider"])
    op.create_index("ix_oauth_tokens_user_id", "oauth_tokens", ["user_id"])

    op.create_table(
        "email_history",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("sender", sa.String(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("opened", sa.Integer(), nullable=True),
        sa.Column("replied", sa.Integer(), nullable=True),
        sa.Column("reply_latency_seconds", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.String(), nullable=True),
    )
    op.create_index("ix_email_history_user_id", "email_history", ["user_id"])
    op.create_index("ix_email_history_sender", "email_history", ["sender"])

    op.create_table(
        "sender_profiles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("sender", sa.String(), nullable=True),
        sa.Column("relationship_weight", sa.Float(), nullable=True),
        sa.Column("email_count", sa.Integer(), nullable=True),
        sa.Column("reply_rate", sa.Float(), nullable=True),
        sa.Column("avg_reply_latency", sa.Float(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.UniqueConstraint("sender", "user_id", name="uq_sender_user"),
    )
    op.create_index("ix_sender_profiles_user_id", "sender_profiles", ["user_id"])
    op.create_index("ix_sender_profiles_sender", "sender_profiles", ["sender"])

    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_conversation_turns_user_id", "conversation_turns", ["user_id"])

    op.create_table(
        "conversation_summaries",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("up_to_turn_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index("ix_conversation_summaries_user_id", "conversation_summaries", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_conversation_summaries_user_id", "conversation_summaries")
    op.drop_table("conversation_summaries")

    op.drop_index("ix_conversation_turns_user_id", "conversation_turns")
    op.drop_table("conversation_turns")

    op.drop_index("ix_sender_profiles_sender", "sender_profiles")
    op.drop_index("ix_sender_profiles_user_id", "sender_profiles")
    op.drop_table("sender_profiles")

    op.drop_index("ix_email_history_sender", "email_history")
    op.drop_index("ix_email_history_user_id", "email_history")
    op.drop_table("email_history")

    op.drop_index("ix_oauth_tokens_user_id", "oauth_tokens")
    op.drop_index("ix_oauth_tokens_provider", "oauth_tokens")
    op.drop_table("oauth_tokens")

    op.drop_index("ix_users_email", "users")
    op.drop_table("users")
